make wslview always use wslpath
wslutilities/wslu pull request #201
Opened 2021-09-03 01:36 UTC by IsaacOscar

Wslview currently dosn't work on paths you've mounted yourself, e.g:
```
mkdir /mnt/win
mount 'C:\Windows' /mnt/win -t drvfs # or the equivalent in /etc/fstab
wslview /mnt/win/notepad.exe
```
Tries to open `\\wsl$\WSL\mnt\win\notepad.exe` which raises an `InvalidOperationException`.

However, `wslpath -w /mnt/win/notepad.exe` reports the correct path as `C:\Windows\notepad.txt`, it also works for pure linux paths like `wslpath -w /var/log/alternatives.log`, which reports `\\wsl$\WSL\var\log\alternatives.log`.

So I've modified the `wslview` script to now just always use `wslpath` to get the windows path.

2021-09-12 18:11 UTC, patrick330602 requested changes
Since `wslview` can also use as a browser, which allows you to open local webpages and websites, this code will break that part.

2021-09-21 00:31 UTC, IsaacOscar commented
I'm not sure what you mean exactly.
My original version works with things like `wslview file:///usr/webpage.html` or `wslview  file:///c/webpage.html`, but it didn't work with `wslview  htttp://github.com`.

So I made a change that bypasses `wslpath` if that fails, so now `wslview http://github.com` will work (along with any other protocol that windows happens to understand).

2021-10-04 03:21 UTC, patrick330602 commented
Sorry for the late reply due to the burnout from the work. After a reread of your code, it is okay to be merged. Sorry for the hassle caused.

2021-10-04 03:21 UTC, patrick330602 approved these changes

2021-10-04 03:21 UTC, merged